In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split



In [2]:
df=pd.read_csv('/kaggle/input/red-wine-dataset/wineQualityReds.csv')
df

Unnamed: 0  fixed.acidity  volatile.acidity  citric.acid  \
0              1            7.4             0.700         0.00   
1              2            7.8             0.880         0.00   
2              3            7.8             0.760         0.04   
3              4           11.2             0.280         0.56   
4              5            7.4             0.700         0.00   
...          ...            ...               ...          ...   
1594        1595            6.2             0.600         0.08   
1595        1596            5.9             0.550         0.10   
1596        1597            6.3             0.510         0.13   
1597        1598            5.9             0.645         0.12   
1598        1599            6.0             0.310         0.47   

      residual.sugar  chlorides  free.sulfur.dioxide  total.sulfur.dioxide  \
0                1.9      0.076                 11.0                  34.0   
1                2.6      0.098                 25.0                  67.0   
2                2.3      0.092                 15.0                  54.0   
3                1.9      0.075                 17.0                  60.0   
4                1.9      0.076                 11.0                  34.0   
...              ...        ...                  ...                   ...   
1594             2.0      0.090                 32.0                  44.0   
1595             2.2      0.062                 39.0                  51.0   
1596             2.3      0.076                 29.0                  40.0   
1597             2.0      0.075                 32.0                  44.0   
1598             3.6      0.067                 18.0                  42.0   

      density    pH  sulphates  alcohol  quality  
0     0.99780  3.51       0.56      9.4        5  
1     0.99680  3.20       0.68      9.8        5  
2     0.99700  3.26       0.65      9.8        5  
3     0.99800  3.16       0.58      9.8        6  
4     0.99780  3.51       0.56      9.4        5  
...       ...   ...        ...      ...      ...  
1594  0.99490  3.45       0.58     10.5        5  
1595  0.99512  3.52       0.76     11.2        6  
1596  0.99574  3.42       0.75     11.0        6  
1597  0.99547  3.57       0.71     10.2        5  
1598  0.99549  3.39       0.66     11.0        6  

[1599 rows x 13 columns]

In [3]:
df.head()

Unnamed: 0  fixed.acidity  volatile.acidity  citric.acid  residual.sugar  \
0           1            7.4              0.70         0.00             1.9   
1           2            7.8              0.88         0.00             2.6   
2           3            7.8              0.76         0.04             2.3   
3           4           11.2              0.28         0.56             1.9   
4           5            7.4              0.70         0.00             1.9   

   chlorides  free.sulfur.dioxide  total.sulfur.dioxide  density    pH  \
0      0.076                 11.0                  34.0   0.9978  3.51   
1      0.098                 25.0                  67.0   0.9968  3.20   
2      0.092                 15.0                  54.0   0.9970  3.26   
3      0.075                 17.0                  60.0   0.9980  3.16   
4      0.076                 11.0                  34.0   0.9978  3.51   

   sulphates  alcohol  quality  
0       0.56      9.4        5  
1       0.68      9.8        5  
2       0.65      9.8        5  
3       0.58      9.8        6  
4       0.56      9.4        5

In [4]:
df.describe().T

count        mean         std      min       25%  \
Unnamed: 0            1599.0  800.000000  461.735855  1.00000  400.5000   
fixed.acidity         1599.0    8.319637    1.741096  4.60000    7.1000   
volatile.acidity      1599.0    0.527821    0.179060  0.12000    0.3900   
citric.acid           1599.0    0.270976    0.194801  0.00000    0.0900   
residual.sugar        1599.0    2.538806    1.409928  0.90000    1.9000   
chlorides             1599.0    0.087467    0.047065  0.01200    0.0700   
free.sulfur.dioxide   1599.0   15.874922   10.460157  1.00000    7.0000   
total.sulfur.dioxide  1599.0   46.467792   32.895324  6.00000   22.0000   
density               1599.0    0.996747    0.001887  0.99007    0.9956   
pH                    1599.0    3.311113    0.154386  2.74000    3.2100   
sulphates             1599.0    0.658149    0.169507  0.33000    0.5500   
alcohol               1599.0   10.422983    1.065668  8.40000    9.5000   
quality               1599.0    5.636023    0.807569  3.00000    5.0000   

                            50%          75%         max  
Unnamed: 0            800.00000  1199.500000  1599.00000  
fixed.acidity           7.90000     9.200000    15.90000  
volatile.acidity        0.52000     0.640000     1.58000  
citric.acid             0.26000     0.420000     1.00000  
residual.sugar          2.20000     2.600000    15.50000  
chlorides               0.07900     0.090000     0.61100  
free.sulfur.dioxide    14.00000    21.000000    72.00000  
total.sulfur.dioxide   38.00000    62.000000   289.00000  
density                 0.99675     0.997835     1.00369  
pH                      3.31000     3.400000     4.01000  
sulphates               0.62000     0.730000     2.00000  
alcohol                10.20000    11.100000    14.90000  
quality                 6.00000     6.000000     8.00000

In [5]:
df.isnull().sum()

Unnamed: 0              0
fixed.acidity           0
volatile.acidity        0
citric.acid             0
residual.sugar          0
chlorides               0
free.sulfur.dioxide     0
total.sulfur.dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64

In [6]:

df['quality'] = [1 if i > 6.5 else 0 for i in df['quality']]
df

Unnamed: 0  fixed.acidity  volatile.acidity  citric.acid  \
0              1            7.4             0.700         0.00   
1              2            7.8             0.880         0.00   
2              3            7.8             0.760         0.04   
3              4           11.2             0.280         0.56   
4              5            7.4             0.700         0.00   
...          ...            ...               ...          ...   
1594        1595            6.2             0.600         0.08   
1595        1596            5.9             0.550         0.10   
1596        1597            6.3             0.510         0.13   
1597        1598            5.9             0.645         0.12   
1598        1599            6.0             0.310         0.47   

      residual.sugar  chlorides  free.sulfur.dioxide  total.sulfur.dioxide  \
0                1.9      0.076                 11.0                  34.0   
1                2.6      0.098                 25.0                  67.0   
2                2.3      0.092                 15.0                  54.0   
3                1.9      0.075                 17.0                  60.0   
4                1.9      0.076                 11.0                  34.0   
...              ...        ...                  ...                   ...   
1594             2.0      0.090                 32.0                  44.0   
1595             2.2      0.062                 39.0                  51.0   
1596             2.3      0.076                 29.0                  40.0   
1597             2.0      0.075                 32.0                  44.0   
1598             3.6      0.067                 18.0                  42.0   

      density    pH  sulphates  alcohol  quality  
0     0.99780  3.51       0.56      9.4        0  
1     0.99680  3.20       0.68      9.8        0  
2     0.99700  3.26       0.65      9.8        0  
3     0.99800  3.16       0.58      9.8        0  
4     0.99780  3.51       0.56      9.4        0  
...       ...   ...        ...      ...      ...  
1594  0.99490  3.45       0.58     10.5        0  
1595  0.99512  3.52       0.76     11.2        0  
1596  0.99574  3.42       0.75     11.0        0  
1597  0.99547  3.57       0.71     10.2        0  
1598  0.99549  3.39       0.66     11.0        0  

[1599 rows x 13 columns]

In [7]:
x = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

In [8]:
x

array([[1.000e+00, 7.400e+00, 7.000e-01, ..., 3.510e+00, 5.600e-01,
        9.400e+00],
       [2.000e+00, 7.800e+00, 8.800e-01, ..., 3.200e+00, 6.800e-01,
        9.800e+00],
       [3.000e+00, 7.800e+00, 7.600e-01, ..., 3.260e+00, 6.500e-01,
        9.800e+00],
       ...,
       [1.597e+03, 6.300e+00, 5.100e-01, ..., 3.420e+00, 7.500e-01,
        1.100e+01],
       [1.598e+03, 5.900e+00, 6.450e-01, ..., 3.570e+00, 7.100e-01,
        1.020e+01],
       [1.599e+03, 6.000e+00, 3.100e-01, ..., 3.390e+00, 6.600e-01,
        1.100e+01]])

In [9]:
y

array([0, 0, 0, ..., 0, 0, 0])

In [10]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size= 0.2, random_state= 0)

In [11]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [12]:
from sklearn.neighbors import KNeighborsClassifier

In [13]:
classifier = KNeighborsClassifier()
classifier.fit(x_train, y_train)


KNeighborsClassifier()

In [14]:
from sklearn.metrics import confusion_matrix, accuracy_score


In [15]:


y_pred = classifier.predict(x_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
print(accuracy_score(y_test, y_pred))

[[273  17]
 [ 14  16]]
0.903125


In [16]:
from sklearn.model_selection import cross_val_score


In [17]:
from sklearn.metrics import confusion_matrix, accuracy_score

In [18]:
y_pred = classifier.predict(x_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
print(accuracy_score(y_test, y_pred))

[[273  17]
 [ 14  16]]
0.903125


In [19]:
accuracies = cross_val_score(estimator = classifier, X = x_train, y = y_train, cv = 10)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

Accuracy: 85.69 %
Standard Deviation: 2.15 %


In [20]:
from sklearn.model_selection import GridSearchCV

In [21]:
parameters = [{'n_neighbors': [3, 5, 7, 9, 11, 13, 15], 'leaf_size': [10, 20, 30, 40, 50], 'metric': ['euclidean']},
              {'n_neighbors': [3, 5, 7, 9, 11, 13, 15], 'leaf_size': [10, 20, 30, 40, 50], 'metric': ['manhattan']},
              {'n_neighbors': [3, 5, 7, 9, 11, 13, 15], 'leaf_size': [10, 20, 30, 40, 50], 'metric': ['chebyshev']},
              {'n_neighbors': [3, 5, 7, 9, 11, 13, 15], 'leaf_size': [10, 20, 30, 40, 50], 'p': [1, 2], 'metric': ['minkowski']}]
grid_search = GridSearchCV(estimator = classifier,
                           param_grid = parameters,
                           scoring = 'accuracy',
                           cv = 10,
                           n_jobs = -1)
grid_search.fit(x_train, y_train)
best_accuracy = grid_search.best_score_
best_parameters = grid_search.best_params_
print("Best Accuracy: {:.2f} %".format(best_accuracy*100))
print("Best Parameters:", best_parameters)

Best Accuracy: 87.10 %
Best Parameters: {'leaf_size': 10, 'metric': 'euclidean', 'n_neighbors': 9}
